name: Continous delivery

on:
  workflow_run:
    workflows: [ "Continous Integration" ]
    types: [ completed ]
    branches: [ master ]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myapp:$(git rev-parse --short HEAD)
